// TARSONS HSE Portal — send-email Edge Function
// ---------------------------------------------------------------------------
// Replaces the email parts of Code.gs (MailApp calls): sendTestEmail,
// sendGenericMail, mailVisitorPass, and the daily sendOverdueAlertEmail
// trigger. Sends via Resend (https://resend.com — free tier is plenty for
// occasional portal notifications).
//
// Deploy with:  supabase functions deploy send-email
// Secrets (set once with `supabase secrets set KEY=value`):
//   RESEND_API_KEY   - from https://resend.com/api-keys
//   FROM_EMAIL       - e.g. "HSE Portal <onboarding@resend.dev>" (or your
//                      own verified domain sender once you add one in Resend)
//   ALERT_EMAIL      - where daily overdue alerts + test emails go
//   SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY - auto-injected by Supabase,
//                      no need to set these yourself. Used only for the
//                      overdueAlertCheck action to read hse_data.
// ---------------------------------------------------------------------------

import { createClient } from "npm:@supabase/supabase-js@2";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY") ?? "";
const FROM_EMAIL = Deno.env.get("FROM_EMAIL") ?? "HSE Portal <onboarding@resend.dev>";
const ALERT_EMAIL = Deno.env.get("ALERT_EMAIL") ?? "";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function json(obj: unknown, status = 200) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function nl2br(s: string) {
  return String(s || "").replace(/\n/g, "<br>");
}

function escapeHtml(s: string) {
  return String(s ?? "").replace(/[&<>"']/g, (m) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[m] as string)
  );
}

// Renders the visitor pass as an HTML table inside the email body. This is
// the closest practical equivalent to the old Apps Script version, which
// generated a real PDF via DocumentApp (a Google Workspace API with no
// direct equivalent in a Deno Edge Function). If you need an actual PDF
// attachment, the cleanest add-on is a small headless-Chrome rendering
// service (e.g. Browserless, or a self-hosted Puppeteer function) that
// converts this same HTML to a PDF and passes it to Resend's `attachments`
// field — ask if you'd like that wired up.
function visitorPassHtml(v: Record<string, string>) {
  const row = (label: string, val?: string) =>
    `<tr><td style="padding:6px 10px;border:1px solid #ccc;font-weight:bold;width:180px;background:#f7f7f7;">${escapeHtml(label)}</td><td style="padding:6px 10px;border:1px solid #ccc;">${escapeHtml(val || "-")}</td></tr>`;
  return `
  <div style="font-family:Arial,Helvetica,sans-serif;max-width:520px;border:1px solid #ddd;padding:22px;border-radius:6px;">
    <h2 style="text-align:center;margin:0 0 4px;">TARSONS PRODUCTS LIMITED</h2>
    <p style="text-align:center;font-style:italic;color:#555;margin:0 0 16px;">HSE Portal — Visitor Pass / Induction Certificate</p>
    <table style="width:100%;border-collapse:collapse;font-size:13px;">
      ${row("Visitor Name", v.name)}
      ${row("Company", v.company)}
      ${row("Mobile Number", v.mobile)}
      ${row("Person to Meet", v.person)}
      ${row("Purpose of Visit", v.purpose)}
      ${row("Factory / Location", v.factory)}
      ${row("PPE Issued", v.ppe || "None")}
      ${row("Safety Briefing Given", v.brief || "No")}
      ${row("Issued Time", v.time)}
    </table>
    <p style="font-style:italic;font-size:12px;color:#444;margin-top:16px;">
      This visitor is declared inducted and cleared for entry into factory premises for the stated purpose only,
      subject to compliance with all site safety rules and PPE requirements.
    </p>
    <p style="font-size:11px;color:#999;margin-top:10px;">
      System-generated by the TARSONS HSE Portal. Valid only for the date of issue.
    </p>
  </div>`;
}

async function sendViaResend(to: string, subject: string, html: string) {
  if (!RESEND_API_KEY) throw new Error("RESEND_API_KEY is not set — run: supabase secrets set RESEND_API_KEY=...");
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ from: FROM_EMAIL, to: [to], subject, html }),
  });
  const data = await res.json().catch(() => null);
  if (!res.ok) throw new Error((data && (data.message || data.error)) || `Resend error (${res.status})`);
  return data;
}

// Mirrors Code.gs's sendOverdueAlertEmail(): reads extinguishers/legal/capa
// from hse_data, checks what's due within 30 days or already overdue, and
// only sends an email if there's something to report.
async function overdueAlertCheck() {
  const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
  const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

  if (!ALERT_EMAIL) return { status: "ok", skipped: "ALERT_EMAIL not configured" };

  const keys = ["extinguishers", "legal", "capa"];
  const { data, error } = await admin.from("hse_data").select("key, value").in("key", keys);
  if (error) throw error;

  const byKey: Record<string, unknown[]> = { extinguishers: [], legal: [], capa: [] };
  for (const row of data || []) byKey[row.key] = Array.isArray(row.value) ? row.value : [];

  const today = new Date();
  const daysUntil = (d: string) => (new Date(d).getTime() - today.getTime()) / 86_400_000;

  type Rec = Record<string, string>;
  const extDue = (byKey.extinguishers as Rec[]).filter((x) => x.due && daysUntil(x.due) <= 30);
  const legalDue = (byKey.legal as Rec[]).filter((x) => x.expiry && daysUntil(x.expiry) <= 30);
  const capaOverdue = (byKey.capa as Rec[]).filter(
    (x) => x.status !== "Closed" && x.due && daysUntil(x.due) < 0
  );

  if (!extDue.length && !legalDue.length && !capaOverdue.length) {
    return { status: "ok", skipped: "nothing due/overdue today" };
  }

  let html = `<h3>TARSONS HSE Portal — Daily Alert Summary</h3>`;
  if (extDue.length) {
    html += `<p><b>FIRE EXTINGUISHERS DUE / OVERDUE:</b></p><ul>`;
    extDue.forEach((x) => (html += `<li>${escapeHtml(x.extID)} (${escapeHtml(x.factory)}) — due ${escapeHtml(x.due)}</li>`));
    html += `</ul>`;
  }
  if (legalDue.length) {
    html += `<p><b>LEGAL / STATUTORY LICENSES EXPIRING:</b></p><ul>`;
    legalDue.forEach((x) => (html += `<li>${escapeHtml(x.license)} (${escapeHtml(x.factory)}) — expires ${escapeHtml(x.expiry)}</li>`));
    html += `</ul>`;
  }
  if (capaOverdue.length) {
    html += `<p><b>OVERDUE CAPA ACTIONS:</b></p><ul>`;
    capaOverdue.forEach(
      (x) => (html += `<li>${escapeHtml(x.desc)} — owner: ${escapeHtml(x.owner)} (${escapeHtml(x.factory)}), was due ${escapeHtml(x.due)}</li>`)
    );
    html += `</ul>`;
  }
  html += `<p>Open the portal to review and update these.</p>`;

  await sendViaResend(ALERT_EMAIL, "HSE Portal: items due or overdue", html);
  return { status: "ok", sent: true };
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const body = await req.json().catch(() => ({}));
    const action = body.action;

    if (action === "overdueAlertCheck") {
      const result = await overdueAlertCheck();
      return json(result);
    }

    if (action === "testEmail") {
      if (!ALERT_EMAIL) return json({ status: "error", message: "ALERT_EMAIL is not set as a function secret." }, 400);
      await sendViaResend(
        ALERT_EMAIL,
        "HSE Portal: Test Email",
        "<p>This is a test email from your TARSONS HSE Portal.</p>" +
          "<p>If you received this, email alerts are configured correctly. The daily automatic alert will only email you when something is actually due or overdue.</p>"
      );
      return json({ status: "ok" });
    }

    if (action === "sendMail") {
      const { to, subject, body: msgBody } = body;
      if (!to) return json({ status: "error", message: "Recipient email address is required." }, 400);
      await sendViaResend(to, subject || "TARSONS HSE Portal Notification", nl2br(msgBody || ""));
      return json({ status: "ok" });
    }

    if (action === "mailVisitorPass") {
      const { to, subject, body: msgBody, visitor } = body;
      if (!to) return json({ status: "error", message: "Recipient email address is required." }, 400);
      const html = `${nl2br(msgBody || "Please find the visitor pass below.")}<br><br>${visitorPassHtml(visitor || {})}`;
      await sendViaResend(to, subject || `Visitor Pass - ${(visitor && visitor.name) || "Visitor"}`, html);
      return json({ status: "ok" });
    }

    return json({ status: "error", message: "Unknown action: " + action }, 400);
  } catch (err) {
    console.error(err);
    return json({ status: "error", message: String((err as Error)?.message || err) }, 500);
  }
});
